server:
  port: 8083

spring:
  application:
    name: event-processing-service
  
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: event-processing-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

aws:
  kinesis:
    stream-name: smartcity-events
    region: us-east-1
  stepfunctions:
    state-machine-arn: arn:aws:states:us-east-1:123456789012:stateMachine:IncidentWorkflow
    region: us-east-1

eureka:
  instance:
    hostname: event-processing
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.smartcity: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

